[Log]
Type = "raw"

[Spider]
CsvPath = "./asset/urls.csv"
ArticleBaseDir = "./data/"
CrawlMaxSleep = 10
RepeatDays = 7
StartHour = 21
StartMin = 30
RecusiveMaxCount = 100

[FaceBook]
Account = "18801090613"
Password = "I7*FUZd5"

[Redis]
Address = "127.0.0.1:6379"
#Address = "172.20.10.237:16148"
Password = ""
DB = 3
Prefix = "fb"
