[Log]
Type = "raw"

[Spider]
CsvPath = "./asset/urls.csv"
ArticleBaseDir = "./data/"
CrawlInterval = 3600
RepeatDays = 7

[FaceBook]
Account = "18810572605"
Password = "4ocjR&SN"

[Redis]
Address = "127.0.0.1:6379"
#Address = "172.20.10.237:16148"
Password = ""
DB = 3
Prefix = "fb"